name = "cosbuilt-website"
compatibility_date = "2026-07-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cosbuilt-db"
database_id = "d2107b08-1f88-4a3c-93a9-65179cfa92a7"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "cosbuilt-uploads"
